"""
Phase 7 — Streamlit Demo
Review Authenticity Detector: predicts if a review is Human or AI-generated.

Run locally:
    streamlit run app.py

Expected files in project root:
    - lr_model.pkl
    - bert_finetuned/   (folder with model + tokenizer)
"""

import pickle
import numpy as np
import streamlit as st
import torch
from transformers import BertTokenizer, BertForSequenceClassification


st.set_page_config(
    page_title="Review Authenticity Detector",
    page_icon="🔍",
    layout="centered",
)


@st.cache_resource
def load_models():
    # Logistic Regression
    with open("lr_model.pkl", "rb") as f:
        lr_pipeline = pickle.load(f)

    # BERT
    tokenizer   = BertTokenizer.from_pretrained("bert_finetuned/")
    bert_model  = BertForSequenceClassification.from_pretrained("bert_finetuned/")
    bert_model.eval()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    bert_model.to(device)

    return lr_pipeline, tokenizer, bert_model, device


lr_pipeline, tokenizer, bert_model, device = load_models()


# UI 
st.title("🔍 Review Authenticity Detector")
st.markdown("Check whether a review was written by a **human** or generated by **AI**.")
st.divider()

review_text  = st.text_area(
    "Paste a review here:",
    height=180,
    placeholder="e.g. The product arrived quickly and works exactly as described...",
)
model_choice = st.radio(
    "Choose model:",
    ["BERT (more accurate)", "Logistic Regression (faster)"],
    horizontal=True,
)
analyse_btn  = st.button("Analyse", type="primary", use_container_width=True)


# Prediction
if analyse_btn:
    if not review_text.strip():
        st.warning("Please enter some review text.")
    else:
        with st.spinner("Analysing..."):
            if "Logistic Regression" in model_choice:
                prob  = lr_pipeline.predict_proba([review_text])[0]
                label = int(lr_pipeline.predict([review_text])[0])
            else:
                inputs = tokenizer(
                    review_text,
                    return_tensors = "pt",
                    truncation     = True,
                    padding        = True,
                    max_length     = 256,
                ).to(device)
                with torch.no_grad():
                    outputs = bert_model(**inputs)
                    prob    = torch.softmax(outputs.logits, dim=1).cpu().numpy()[0]
                label = int(np.argmax(prob))

        st.divider()

        if label == 1:
            st.error("🤖 AI-Generated")
        else:
            st.success("✅ Human-Written")

        col1, col2 = st.columns(2)
        col1.metric("Human Probability", f"{prob[0]*100:.1f}%")
        col2.metric("AI Probability",    f"{prob[1]*100:.1f}%")
        st.caption(f"Model used: {model_choice}")
